Added event filter UI
utmmcss/mcss-website-frontend pull request #28
Opened 2021-11-20 19:43 UTC by nigow

### Ticket
[Ticket Link](https://trello.com/c/jNpQzPMO/33-event-page-create-events-filter-bar)

### What is changed / added
- Added filters
- No internal logic added

### Screenshots
![Screen Shot 2021-11-21 at 4 42 31](https://user-images.githubusercontent.com/64772347/142739036-b8c771f6-da34-4404-9b27-998358e14304.png)

2021-11-28 20:01 UTC, TheFatPanda97 commented on components/Common/EventFilter.tsx
> +    <button type="button" onClick={handleClick} className="m-5">
```suggestion
    <button type="button" onClick={() => setClicked(!clicked)} className="m-5">
```

2021-11-28 20:01 UTC, TheFatPanda97 commented on components/Common/EventFilter.tsx
> +  };
```suggestion
```
we can make this inline

2021-11-28 20:06 UTC, TheFatPanda97 commented on components/Common/EventFilter.tsx
> +        : <p style={{ color: '#7d7b76' }}>{optionName}</p>}
```suggestion
        <p style={{ color: clicked ? '#7d25af' :  '#7d7b76' }}>{optionName}</p>
```

2021-11-28 20:09 UTC, TheFatPanda97 requested changes
looks good, just small changes here and there

2021-12-07 19:41 UTC, nigow commented
@TheFatPanda97 ok

2021-12-09 02:25 UTC, TheFatPanda97 approved these changes

2021-12-16 00:52 UTC, merged