Added General Events Section
utmmcss/mcss-website-frontend pull request #29
Opened 2021-11-21 00:01 UTC by NerajM

### Ticket
[Ticket Link](https://trello.com/c/UKTCFiJZ/28-event-page-create-general-event-section)

### What is changed / added
- implemented the general events section of the event page. 

### Screenshots
<img width="944" alt="GeneralEventsSection" src="https://user-images.githubusercontent.com/35711461/142744365-072769aa-f518-47a3-98ee-1d7e83b954aa.PNG">

2021-11-21 00:29 UTC, nigow commented on components/Common/GeneralEvents.tsx
> +            <div className="tag">Food</div>
Can this be part of the props too?

2021-11-28 19:58 UTC, TheFatPanda97 commented on components/Common/GeneralEvents.tsx
> +            <div className="tag">Food</div>
yep agreed

2021-11-28 19:59 UTC, TheFatPanda97 requested changes
looks good, just need to fix the small change Tairi suggested

2021-12-15 02:56 UTC, TheFatPanda97 approved these changes

2021-12-15 04:07 UTC, nigow approved these changes

2021-12-16 00:52 UTC, merged